Implemented Announcements Section
cpinitiative/cpinitiative pull request #191
Opened 2024-02-02 19:26 UTC by Vinceyou1

2024-02-02 20:58 UTC, mjh316 requested changes

2024-02-02 20:58 UTC, mjh316 commented on src/components/announcements/a.module.css
> +    all: unset;
Could we rename this file from a.module.css to something relevant like `unset-all-tailwind.css` or something?

2024-02-02 20:59 UTC, mjh316 commented
<img width="607" alt="Screenshot 2024-02-02 at 12 59 43 PM" src="https://github.com/cpinitiative/cpinitiative/assets/61671361/5eaccdb4-ed66-4f50-9fec-948da9741242">
Also, build seems to be failing for this reason

2024-02-04 02:21 UTC, mjh316 commented
Bump @Vinceyou1 ?

2024-02-04 03:34 UTC, Vinceyou1 commented
@mjh316 I'm not sure where the errors are coming from, can you see if fixing the merge conflicts will get rid of them? I don't have write access so I can't resolve them myself.

2024-02-04 04:57 UTC, mjh316 commented
@Vinceyou1 Fixed the merge conflict, can you take a look at my review comments? Thank you!

2024-02-04 05:48 UTC, mjh316 requested changes

2024-02-04 19:02 UTC, Vinceyou1 commented on next.config.js
@mjh316 I've been working on this for like 2 hours and I can't get the issues to go away while keeping the MDX. Can we just reopen this PR? https://github.com/cpinitiative/cpinitiative/pull/186. Everything works fine here for some reason, though it could be changes after this PR that are causing issues.

2024-02-04 19:03 UTC, Vinceyou1 commented on next.config.js
Actually, is there any specific reason we're using esm modules? Getting rid of those seems to fix this

2024-02-06 05:15 UTC, mjh316 commented on next.config.js
Oh wait - we were using those for react-snowfall for the tournament page, but I think we didn't end up using react-snowfall. Do you want to go ahead and switch back? The postcss config and everything, too

2024-02-06 05:16 UTC, mjh316 commented on next.config.js
@Vinceyou1

2024-02-06 19:15 UTC, Vinceyou1 commented on next.config.js
@mjh316 yeah, I think that should fix the issues

2024-02-07 22:12 UTC, Vinceyou1 commented
@mjh316 can you see if the preview deployment builds properly now?

2024-02-07 22:42 UTC, mjh316 commented
<img width="1201" alt="Screenshot 2024-02-07 at 2 42 15 PM" src="https://github.com/cpinitiative/cpinitiative/assets/61671361/84c44b15-84de-4228-8495-01c7a8473425">
@Vinceyou1 could you build locally and see if you get the attached error?

2024-02-08 02:23 UTC, Vinceyou1 commented
@mjh316 I just installed zod, it fixed the issues locally

2024-02-08 05:00 UTC, merged