add indigo
cpinitiative/cpinitiative pull request #214
Opened 2024-08-29 23:06 UTC by shine00chang

https://discord.com/channels/754884077542441002/877330703853961268/1278460144220504277

2024-08-30 17:11 UTC, cskitty approved these changes

2024-09-02 00:56 UTC, Vinceyou1 requested changes
could you also comment out the two "Register Now" buttons under the class levels, and disable the register button in case someone manages to get to the registration page anyway?

2024-09-06 03:45 UTC, shine00chang commented
https://discord.com/channels/754884077542441002/877330703853961268/1281451990668410990
https://discord.com/channels/754884077542441002/877330703853961268/1281454953143210014

2024-09-07 17:52 UTC, Vinceyou1 requested changes
classes end in December, not November

2024-09-10 16:37 UTC, merged